mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/taewan/hm/**/mapper/*Mapper.xml
  
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: tmdb
    password: TMDB
  application:
    name: tmdb-web

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 50MB
#      max-request-size: 50MB